import Vue from 'vue';

import { 
    ClickOutside, 
    Intersect,
    Resize, 
    Ripple, 
    Scroll, 
    Touch 
} from 'vuetify/lib/directives';

import { 
    VDialogBottomTransition,
    VExpandTransition, 
    VFadeTransition,
    VScaleTransition,
    VSlideYTransition,
    VSlideYReverseTransition,
} from 'vuetify/lib/components/transitions';

import Vuetify, {
    VApp,
    VAppBar,
    VAppBarNavIcon,
    VAvatar,
    VBtn,
    VBtnToggle,
    VCard,
    VCardText,
    VCardActions,
    VContainer,
    VContent,
    VCol,
    VCombobox,
    VCheckbox,
    VDataTable,
    VDialog,
    VDivider,
    VExpansionPanel,
    VExpansionPanelContent,
    VExpansionPanelHeader,
    VExpansionPanels,
    VFooter,
    VHover,
    VIcon,
    VImg,
    VList,
    VListItem,
    VListItemAction,
    VListItemAvatar,
    VListItemContent,
    VListItemGroup,
    VListItemIcon,
    VListItemSubtitle,
    VListItemTitle,
    VMenu,
    VNavigationDrawer,
    VOverlay,
    VProgressCircular,
    VProgressLinear,
    VResponsive,
    VRadio,
    VRadioGroup,
    VRow,
    VSelect,
    VSimpleTable,
    VSheet,
    VSpacer,
    VSnackbar,
    VSubheader,
    VSystemBar,
    VSwitch,
    VTab,
    VTabItem,
    VTabs,
    VTabsItems,
    VTextarea,
    VTextField,
    VToolbar,
    VToolbarTitle,
    VTooltip

} from 'vuetify/lib';

Vue.use(Vuetify, {
    components: {
        VApp,
        VAppBar,
        VAppBarNavIcon,
        VAvatar,
        VBtn,
        VBtnToggle,
        VCard,
        VCardText,
        VCardActions,
        VContainer,
        VContent,
        VCol,
        VCombobox,
        VCheckbox,
        VDataTable,
        VDialog,
        VDialogBottomTransition,
        VDivider,
        VExpandTransition,
        VExpansionPanel,
        VExpansionPanelContent,
        VExpansionPanelHeader,
        VExpansionPanels,
        VFadeTransition,
        VFooter,
        VHover,
        VIcon,
        VImg,
        VList,
        VListItem,
        VListItemAction,
        VListItemAvatar,
        VListItemContent,
        VListItemGroup,
        VListItemIcon,
        VListItemSubtitle,
        VListItemTitle,
        VMenu,
        VNavigationDrawer,
        VOverlay,
        VProgressCircular,
        VProgressLinear,
        VResponsive,
        VRadio,
        VRadioGroup,
        VRow,
        VSelect,
        VSimpleTable,
        VSheet,
        VScaleTransition,
        VSlideYTransition,
        VSlideYReverseTransition,
        VSpacer,
        VSnackbar,
        VSubheader,
        VSystemBar,
        VSwitch,
        VTab,
        VTabItem,
        VTabs,
        VTabsItems,
        VTextarea,
        VTextField,
        VToolbar,
        VToolbarTitle,
        VTooltip
    },

    directives: {
        ClickOutside, 
        Intersect,
        Resize, 
        Ripple, 
        Scroll, 
        Touch 
    }
});

export default new Vuetify({
    icons: {
        iconfont: 'md',
    }
});